---

- name: Restart tcg service
  systemd:
    name: tcg
    state: started
    enabled: yes
    daemon_reload: yes

- name: Wait for tcg service become ready
  wait_for:
    host: 127.0.0.1
    port: 8084
    timeout: 300
    delay: 10
