---

- name: Upload MySQL configuration file
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    backup: yes
  notify: restart mysqld

- name: Create systemd directory
  file:
    path: /etc/systemd/system/mysqld.service.d
    state: directory
    mode: 0755

- name: Upload systemd-file
  copy:
    src: custom.conf
    dest: /etc/systemd/system/mysqld.service.d/custom.conf
  notify: restart mysqld
